version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1011
      - PGID=1011
      - PORT_RANGE=30000:30010
    volumes:
      - /tazb-media/NETBOOT/administrator/docker-files/config:/config
      - /tazb-media/NETBOOT/administrator/docker-files/assets:/assets
    ports:
      - 3000:3000
      - 69
      - 8810
    restart: unless-stopped